### ISSUE TITLE
problem running app

### ISSUE THREAD

**Issue by johntday** [awatson1978/panel-layout#1]
Stand back while Meteorite does its thing
✓ mousetrap
    tag: https://github.com/awatson1978/mousetrap.git#v1.5.2
ERROR: 128 Command failed: fatal: reference is not a tree: 77fef1e9dd64fc99cf0fc128dcb10d038c0fe860

STDOUT:  

STDERR: fatal: reference is not a tree: 77fef1e9dd64fc99cf0fc128dcb10d038c0fe860

/usr/local/lib/node_modules/meteorite/lib/sources/git.js:181
            self.checkoutType + ": " + (self.commit || self.head);
                                     ^
There was a problem checking out tag: 77fef1e9dd64fc99cf0fc128dcb10d038c0fe860

**Comment by awatson1978** [comment]
Yeah, this one is still on `0.8.0.1`.  Haven't gotten around to updating it to 1.0.  Sorry 'bout that.

**Comment by awatson1978** [comment]
Just upgraded the app to Meteor 1.0.  You should be good to go.  Enjoy!
